### ISSUE TITLE
After Install(from Wordpress) and activating I get an error

### ISSUE THREAD

**Issue by Mannshoch** [lebleut/tooltipy#2]
`Warning: array_key_exists() expects parameter 2 to be array, boolean given in /www/wp-content/plugins/bluet-keywords-tooltip-generator/advanced/functions.php on line 226 `

**Comment by lebleut** [comment]
Hi @Mannshoch 

Fortunately it's fixed here on Github but not yet deployed on Wordpress.org
You can download it from this repository and test it

Thanks
